# Generated by Django 3.2.3 on 2022-01-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
