# Generated by Django 3.2.3 on 2022-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopper', '0003_auto_20220111_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(default='4568172.jpg', upload_to='media'),
        ),
        migrations.DeleteModel(
            name='UpdateProfileImage',
        ),
    ]
