# Generated by Django 3.2.3 on 2022-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopper', '0005_auto_20220112_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='zip',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
