# Generated by Django 3.2.3 on 2022-01-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopper', '0006_auto_20220112_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(default='4568172.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='zip',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
