# Generated by Django 3.2.3 on 2022-01-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopper', '0008_auto_20220117_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofileimage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='updateprofileimage',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_no',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
