# Generated by Django 3.2.3 on 2022-01-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopper', '0009_auto_20220117_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(max_length=1000, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
