# Generated by Django 3.2.3 on 2022-02-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shopper', '0014_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Scheduled', 'Scheduled'), ('Shipped', 'Shipped'), ('In Progress', 'In Progress')], default='In Progress', max_length=500),
        ),
    ]
